/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kelinlang_network_socket_SocketDemo */

#ifndef _Included_com_kelinlang_network_socket_SocketDemo
#define _Included_com_kelinlang_network_socket_SocketDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kelinlang_network_socket_SocketDemo
 * Method:    startServer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_kelinlang_network_socket_SocketDemo_startServer
  (JNIEnv *, jobject);

/*
 * Class:     com_kelinlang_network_socket_SocketDemo
 * Method:    stopServer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_kelinlang_network_socket_SocketDemo_stopServer
  (JNIEnv *, jobject);

/*
 * Class:     com_kelinlang_network_socket_SocketDemo
 * Method:    startClient
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_kelinlang_network_socket_SocketDemo_startClient
  (JNIEnv *, jobject);

/*
 * Class:     com_kelinlang_network_socket_SocketDemo
 * Method:    stopClient
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_kelinlang_network_socket_SocketDemo_stopClient
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
