/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kelinlang_superdemo_MainActivity */

#ifndef _Included_com_kelinlang_superdemo_MainActivity
#define _Included_com_kelinlang_superdemo_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kelinlang_superdemo_MainActivity
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_kelinlang_superdemo_MainActivity_stringFromJNI
  (JNIEnv *, jobject);

/*
 * Class:     com_kelinlang_superdemo_MainActivity
 * Method:    get
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_kelinlang_superdemo_MainActivity_get
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_kelinlang_superdemo_MainActivity
 * Method:    getLine
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_kelinlang_superdemo_MainActivity_getLine
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
